% clc;clear
% syms a b s c1 c2 c3 c4 c5 o1 n1 o2 n2 o3 n3 o4 n4 o5 n5 ...
%     tall tann kao fan fcm lcm lcm2 fvm lvm fmix lmix lmix2 fmix2...
%     fmix2_ lmix2_ lmix2_2 fmix2_2
% 
% % jacobian([fcm-fan, lcm-lvm,lcm2-lvm,fvm-fan,lmix-lmix2,lmix2_-lmix2_2...
% %     fmix-fmix2, fmix2_-fmix2_2, fmix2_-fmix],...
% %     [a,b,s,c1,c2,c3,c4,c5,o1,n1,o2,n2,o3,n3,o4,n4,o5,n5 ...
% %     tall,tann,kao,fan,fcm,lcm,lcm2,fvm,lvm,fmix,lmix,lmix2,fmix2...
% %     fmix2_,lmix2_,lmix2_2,fmix2_2])
% 
% % ctrlr-ctrlt
% 
% 
% jacobian([lmix-lmix2,...
%     fmix-fmix2],...
%     [a,b,s,c1,c2,c3,c4,c5,o1,n1,o2,n2,o3,n3,o4,n4,o5,n5 ...
%     tall,tann,kao,fan,fcm,lcm,lcm2,fvm,lvm,fmix,lmix,lmix2,fmix2...
%     fmix2_,lmix2_,lmix2_2,fmix2_2])


% clc;clear
% syms a b s c3 o3 n3 ...
%     tall tann kao fmix lmix lmix2 fmix2...
%     
% jacobian([lmix-lmix2,...
%     fmix-fmix2],...
%     [a, b, s, c3, o3 ,n3 ...
%     tall ,tann ,kao ,fmix ,lmix ,lmix2 ,fmix2])

clc;clear
syms a b s c3 o3 n3 ...
    tall tann kao fmix lmix lmix2 fmix2...
    
jacobian([lmix-lmix2,...
    fmix-fmix2],...
    [a, b, s, c3, o3 ,n3 ...
    tall ,tann ,kao ,fmix ,lmix ,lmix2 ,fmix2])

